services:
  #---------------------------------------------------------
  # SQL Server (Versão Super Leve: Azure SQL Edge)
  #---------------------------------------------------------
  # Utilizamos a imagem do Azure SQL Edge, que é uma engine 
  # do SQL Server 2019 super otimizada para IoT e ARM, mas 
  # que roda perfeitamente em x64. Ele consome <500MB de RAM, 
  # sendo drasticamente mais leve que o SQL Server Express/Developer.
  #---------------------------------------------------------
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sqlformys-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    volumes:
      - sqldata:/var/opt/mssql

  #---------------------------------------------------------
  # Backend API (Go)
  #---------------------------------------------------------
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: sqlformys-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=${PORT}
      - DB_DRIVER=${DB_DRIVER}
      # String de conexão lida do .env (usando o alias 'db' do compose)
      - DB_DSN=${DB_DSN}

volumes:
  sqldata:
    name: sqlformys-sqldata
